<a href="https://colab.research.google.com/github/Pradeep24032004/data_science/blob/main/numpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#converting list to numpy array
import numpy as np
list1 = list(range(50))
array1 = np.array(list1)
print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [ ]:
#creating a random array random
import numpy as np
from numpy import random
#printing random number
x = random.randint(1,101)
print(x)
#ana array of random numbers of size 5
x1 = random.randint(1, 101, size=(5))
print(x1)

3
[64 39 77 75 38]


In [ ]:
#creating a 2D array
x2 = random.randint(1, 101, size=(5, 4))
print("2D array",x2)
#creating 3D array
x3 = random.randint(1, 101, size= (3, 5, 4))
print("3D array", x3)
#converting array into list
l1 = list(x3)
print("list", l1)

2D array [[17 41 88 53]
 [ 2 10 73 49]
 [42  4 52 13]
 [37 16  9 10]
 [34 26 71 27]]
3D array [[[ 59  71  79  82]
  [  8  23  39  90]
  [ 97  41  60  89]
  [ 31  43  23  54]
  [ 99  21  86  20]]

 [[ 20  86  95  69]
  [ 89  72  31  16]
  [ 87 100   3  40]
  [  4  84  55  21]
  [ 87  53   3   8]]

 [[ 42   8  15  82]
  [  5  23  87  91]
  [ 27  99  35  67]
  [ 88  10  36  89]
  [ 85  37  41  34]]]
list [array([[59, 71, 79, 82],
       [ 8, 23, 39, 90],
       [97, 41, 60, 89],
       [31, 43, 23, 54],
       [99, 21, 86, 20]]), array([[ 20,  86,  95,  69],
       [ 89,  72,  31,  16],
       [ 87, 100,   3,  40],
       [  4,  84,  55,  21],
       [ 87,  53,   3,   8]]), array([[42,  8, 15, 82],
       [ 5, 23, 87, 91],
       [27, 99, 35, 67],
       [88, 10, 36, 89],
       [85, 37, 41, 34]])]


In [ ]:
import numpy as np
a = np.array([[9,2], [3, 4]])
a = a + 1
print(a)
print("sum is", a.sum())
print("data type:", a.dtype)
#converting data types
a1 = np.array([1, 2], dtype = float)
print(a1, "data type:", a1.dtype)

[[10  3]
 [ 4  5]]
sum is 22
data type: int64
[1. 2.] data type: float64


In [ ]:
#summing up two arrays
import numpy as np
arr1 = np.array([[4, 7], [2, 6]], dtype = np.float64)
arr2 = np.array([[3, 6], [2, 8]], dtype = np.float64)
sum = np.add(arr1, arr2)
print(sum)
#summing up all values in array1
sum1 = np.sum(arr1)
print(sum1)
#squaring up all values in array1
square1 = np.square(arr1)
print(square1)
#sqaure root of numbers
sqrt1 = np.sqrt(arr1)
print(sqrt1)

[[ 7. 13.]
 [ 4. 14.]]
19.0
[[16. 49.]
 [ 4. 36.]]
[[2.         2.64575131]
 [1.41421356 2.44948974]]


In [ ]:
#Transpose
Trans_arr1 = arr1.T
print(Trans_arr1)

[[4. 2.]
 [7. 6.]]


In [ ]:
#creating an array using Array function
import numpy as np
print(np.arange(5,15))
print(np.arange(1,30,2))
print(np.arange(2,40,5,dtype=float))
print(np.identity(5))
print(np.identity(5, dtype=int))

[ 5  6  7  8  9 10 11 12 13 14]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
[ 2.  7. 12. 17. 22. 27. 32. 37.]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
#creating an identity matrix with offset value
print(np.eye(5, k=1, dtype=int)) #here offset value is denoted by k
print(np.eye(5, k=-2, dtype=int))

[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


In [ ]:
#example1
A = [
    ["student1",90,78,67,90,98],
    ["student2",89,78,87,98,76],
    ["student3",67,76,85,67,90],
    ["student4",90,78,67,76,98],
    ["student5",89,78,67,98,67]
]
array_1 = np.array(A)
#accessing different things
#array[start:stop:stepsize, start:stop:stepsize, start:stop:stepsize]
print(array_1[:, :2])
print(array_1[:, 1::2])
print(array_1[::2, :])
#finding average of a subject
sub_1 = array_1[:,1].astype(int) #extract the second column values and converting it into int
average = sub_1.mean()
print("sub 1 average", average)
total_marks = array_1[:, 1:].astype(int)
total_average= total_marks.mean()
print("average of all subjects", total_average)
total_sum = array_1[:, 1:].astype(int)
print("total sum", total_sum.sum())
sub_total_each_student = array_1[:, 1:].astype(int)
total_of_each_student = sub_total_each_student.sum(axis = 1) #refers to each row if axis=1 and if axis=0 refers to each column
print("total marks of each student",total_of_each_student)
subwise_total = sub_total_each_student.sum(axis=0)
print("sub wise total", subwise_total)
subject_1 = array_1[:,1].astype(int)
subject_2 = array_1[:,2].astype(int)
print("if sub 1 > sub 2", array_1[subject_1 > subject_2])


[['student1' '90']
 ['student2' '89']
 ['student3' '67']
 ['student4' '90']
 ['student5' '89']]
[['90' '67' '98']
 ['89' '87' '76']
 ['67' '85' '90']
 ['90' '67' '98']
 ['89' '67' '67']]
[['student1' '90' '78' '67' '90' '98']
 ['student3' '67' '76' '85' '67' '90']
 ['student5' '89' '78' '67' '98' '67']]
sub 1 average 85.0
average of all subjects 81.76
total sum 2044
total marks of each student [423 428 385 409 399]
sub wise total [425 388 373 429 429]
if sub 1 > sub 2 [['student1' '90' '78' '67' '90' '98']
 ['student2' '89' '78' '87' '98' '76']
 ['student4' '90' '78' '67' '76' '98']
 ['student5' '89' '78' '67' '98' '67']]


In [ ]:
#count non zeros
import numpy as np
arr = np.array([0,1,2,3,0,4,5,0])
print(np.count_nonzero(arr))
#printing the sum of all subject wise marks of all students
marks = np.array([[89,98,78,67,58],
                  [68,73,81,94,100]])
marks.sum(axis=0) #columnwise sum
marks.sum(axis=1) #row wise sum

5


array([390, 416])

In [ ]:
#print all the values greater than 15
sub_a = np.array([10,20,22,31,16,15])
print("values greater than 15",sub_a[sub_a > 15])
print("whether elements greater than 15", sub_a>15)
#by using where condition
print("by using where condition",np.where(sub_a > 15))
#printing the unique values in an array
a = np.array(['a','a','b','c','d','d'])
print("unique occurences", np.unique(a))

values greater than 15 [20 22 31 16]
whether elements greater than 15 [False  True  True  True  True False]
by using where condition (array([1, 2, 3, 4]),)
unique occurences ['a' 'b' 'c' 'd']
